CREATE TABLE IF NOT EXISTS sarga_enterprise_audit (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  audit_id VARCHAR(36) NOT NULL UNIQUE,
  timestamp TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  user_id_internal INT,
  username VARCHAR(100),
  employee_name VARCHAR(255),
  user_role VARCHAR(50),
  branch_id INT,
  branch_name VARCHAR(255),
  department VARCHAR(100),
  module VARCHAR(100) NOT NULL,
  action_type VARCHAR(50) NOT NULL,
  record_type VARCHAR(100),
  record_id VARCHAR(100),
  document_number VARCHAR(200),
  previous_values JSON,
  new_values JSON,
  changed_fields JSON,
  ip_address VARCHAR(45),
  device_name VARCHAR(255),
  browser VARCHAR(255),
  operating_system VARCHAR(255),
  session_id VARCHAR(255),
  api_endpoint VARCHAR(500),
  response_status INT,
  success TINYINT(1) DEFAULT 1,
  error_message TEXT,
  reason_remarks TEXT,
  latitude DECIMAL(10,7),
  longitude DECIMAL(10,7),
  duration_ms INT,
  previous_hash VARCHAR(64),
  current_hash VARCHAR(64) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_audit_timestamp (timestamp),
  INDEX idx_audit_user (user_id_internal),
  INDEX idx_audit_branch (branch_id),
  INDEX idx_audit_module (module),
  INDEX idx_audit_action (action_type),
  INDEX idx_audit_record (record_id),
  INDEX idx_audit_success (success),
  INDEX idx_audit_document (document_number(100)),
  INDEX idx_audit_date (created_at)
);

CREATE TABLE IF NOT EXISTS sarga_audit_archive (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  original_id BIGINT NOT NULL,
  audit_id VARCHAR(36) NOT NULL UNIQUE,
  timestamp TIMESTAMP(6) NOT NULL,
  user_id_internal INT,
  username VARCHAR(100),
  employee_name VARCHAR(255),
  user_role VARCHAR(50),
  branch_id INT,
  branch_name VARCHAR(255),
  department VARCHAR(100),
  module VARCHAR(100) NOT NULL,
  action_type VARCHAR(50) NOT NULL,
  record_type VARCHAR(100),
  record_id VARCHAR(100),
  document_number VARCHAR(200),
  previous_values JSON,
  new_values JSON,
  changed_fields JSON,
  ip_address VARCHAR(45),
  device_name VARCHAR(255),
  browser VARCHAR(255),
  operating_system VARCHAR(255),
  session_id VARCHAR(255),
  api_endpoint VARCHAR(500),
  response_status INT,
  success TINYINT(1) DEFAULT 1,
  error_message TEXT,
  reason_remarks TEXT,
  latitude DECIMAL(10,7),
  longitude DECIMAL(10,7),
  duration_ms INT,
  previous_hash VARCHAR(64),
  current_hash VARCHAR(64) NOT NULL,
  archived_by INT,
  archived_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_archive_audit_id (audit_id),
  INDEX idx_archive_date (archived_at)
);
